# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll"
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-seo-tag"
  gem "kramdown-parser-gfm"
  gem "webrick"
end
